In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'https://github.com/YBI-Foundation/Dataset/raw/main/Bike%20Prices.csv')

In [3]:
df.head

<bound method NDFrame.head of       Brand                      Model  Selling_Price  Year Seller_Type  \
0       TVS                 TVS XL 100          30000  2017  Individual
1     Bajaj              Bajaj  ct 100          18000  2017  Individual
2        Yo                   Yo Style          20000  2011  Individual
3     Bajaj         Bajaj Discover 100          25000  2010  Individual
4     Bajaj         Bajaj Discover 100          24999  2012  Individual
...     ...                        ...            ...   ...         ...
1056  Royal  Royal Enfield Electra 5 S          90000  2012  Individual
1057   Hero            Hero Honda Hunk          20000  2010  Individual
1058  Bajaj     Bajaj Pulsar 220 DTS-i          60000  2014  Individual
1059   Hero     Hero Honda CBZ extreme          40000  2009  Individual
1060   Hero     Hero Honda CBZ extreme          35000  2012  Individual

          Owner  KM_Driven  Ex_Showroom_Price
0     1st owner       8000            30490.0
1     1st owner      35000            32000.0
2     1st owner      10000            37675.0
3     1st owner      43000            42859.0
4     2nd owner      35000            42859.0
...         ...        ...                ...
1056  1st owner      40000                NaN
1057  1st owner      17000                NaN
1058  1st owner      16000                NaN
1059  1st owner      50000                NaN
1060  1st owner      60000                NaN

[1061 rows x 8 columns]>

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1061 entries, 0 to 1060
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              1061 non-null   object
 1   Model              1061 non-null   object
 2   Selling_Price      1061 non-null   int64
 3   Year               1061 non-null   int64
 4   Seller_Type        1061 non-null   object
 5   Owner              1061 non-null   object
 6   KM_Driven          1061 non-null   int64
 7   Ex_Showroom_Price  626 non-null    float64
dtypes: float64(1), int64(3), object(4)
memory usage: 66.4+ KB

In [5]:
df=df.dropna()

In [6]:
df.describe()

       Selling_Price         Year      KM_Driven  Ex_Showroom_Price
count     626.000000   626.000000     626.000000       6.260000e+02
mean    59445.164537  2014.800319   32671.576677       8.795871e+04
std     59904.350888     3.018885   45479.661039       7.749659e+04
min      6000.000000  2001.000000     380.000000       3.049000e+04
25%     30000.000000  2013.000000   13031.250000       5.485200e+04
50%     45000.000000  2015.000000   25000.000000       7.275250e+04
75%     65000.000000  2017.000000   40000.000000       8.703150e+04
max    760000.000000  2020.000000  585659.000000       1.278000e+06

In [7]:
df[['Brand']].value_counts()

Brand
Honda       170
Bajaj       143
Hero        108
Yamaha       94
Royal        40
TVS          23
Suzuki       18
KTM           6
Mahindra      6
Kawasaki      4
UM            3
Activa        3
Harley        2
Vespa         2
BMW           1
Hyosung       1
Benelli       1
Yo            1
dtype: int64

In [8]:
df[['Model']].value_counts()

Model
Honda Activa [2000-2015]                      23
Honda CB Hornet 160R                          22
Bajaj Pulsar 180                              20
Yamaha FZ S V 2.0                             16
Bajaj Discover 125                            16
                                              ..
Royal Enfield Thunderbird 500                  1
Royal Enfield Continental GT [2013 - 2018]     1
Royal Enfield Classic Stealth Black            1
Royal Enfield Classic Squadron Blue            1
Yo Style                                       1
Length: 183, dtype: int64

In [9]:
df[['Seller_Type']].value_counts()

Seller_Type
Individual     623
Dealer           3
dtype: int64

In [10]:
df[['Owner']].value_counts()

Owner
1st owner    556
2nd owner     66
3rd owner      3
4th owner      1
dtype: int64

In [11]:
df.columns

Index(['Brand', 'Model', 'Selling_Price', 'Year', 'Seller_Type', 'Owner',
       'KM_Driven', 'Ex_Showroom_Price'],
      dtype='object')

In [12]:
df.shape

(626, 8)

In [13]:
df.replace({'Seller_Type':{'Individual':0,'Dealer':1}},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [14]:
df.replace({'Owner':{'1st Owner':0,'2nd Owner':1,'3rd Owner':2,'4th Owner':3}},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [15]:
y=df['Selling_Price']

In [16]:
y.shape

(626,)

In [17]:
y

0       30000
1       18000
2       20000
3       25000
4       24999
        ...
621    330000
622    300000
623    425000
624    760000
625    750000
Name: Selling_Price, Length: 626, dtype: int64

In [18]:
x=df[['Year','Seller_Type','Owner','KM_Driven','Ex_Showroom_Price']]

In [19]:
x.shape

(626, 5)

In [20]:
x

     Year  Seller_Type      Owner  KM_Driven  Ex_Showroom_Price
0    2017            0  1st owner       8000            30490.0
1    2017            0  1st owner      35000            32000.0
2    2011            0  1st owner      10000            37675.0
3    2010            0  1st owner      43000            42859.0
4    2012            0  2nd owner      35000            42859.0
..    ...          ...        ...        ...                ...
621  2014            0  4th owner       6500           534000.0
622  2011            0  1st owner      12000           589000.0
623  2017            0  2nd owner      13600           599000.0
624  2019            0  1st owner       2800           752020.0
625  2013            0  2nd owner      12000          1278000.0

[626 rows x 5 columns]

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3,random_state=182529)

In [23]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((438, 5), (188, 5), (438,), (188,))

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr=LinearRegression()

In [26]:
lr.fit(x_train,y_train)

ValueError: ignored

In [27]:
y_pred=lr.predict(x_test)

ValueError: ignored

In [ ]:
y_pred.shape

In [ ]:
y_pred

NameError: ignored